version: 0.2



env:

  variables:

    TF_VERSION: "0.10.7"

  #parameter-store:
   #     AWS_ACCESS_KEY_ID_PARAM: /CodeBuild/access_key
    #    AWS_SECRET_ACCESS_KEY_PARAM: /CodeBuild/secret_key
   
  secrets-manager:
     /CodeBuild/Secrets: arn:aws:secretsmanager:us-east-1:361061974256:secret:/CodeBuild/Secrets-8yxVO9
        
phases:


  install:

    commands:

      # install required binary

      - "curl -s -qL -o /usr/bin/jq https://stedolan.github.io/jq/download/linux64/jq"

      - "chmod +x /usr/bin/jq"

      - "cd /usr/bin"

      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"

      - "unzip -o terraform.zip"
  
      #aws cli installation
      
      - apt-get install awscli -y
      
      #yarn installation 
      
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg |  apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" |  tee /etc/apt/sources.list.d/yarn.list
      - apt update &&  apt install yarn -y
      
      
      
  pre_build:

    commands:
    
      - terraform -v
      - aws --version
      - yarn --version



  build:

    commands:
    
     - cd "$CODEBUILD_SRC_DIR"
     
     - terraform init 
     
     - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PARAM
     
     - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PARAM
     
     - export export AWS_REGION=us-east-1
     
     - echo $AWS_ACCESS_KEY_ID
     - echo $AWS_SECRET_ACCESS_KEY
     
     #- terraform plan 
     
     #- terraform apply 
     

  post_build:

    commands:
      
      - terraform show
      # - aws s3 ls
      #- terraform plan -out=s3tfplan
      #- pwd
      #- ls -la .terraform/
      #- aws s3 cp s3tfplan s3://terraformbucket1234232/
      #- terraform plan -destroy
      #- terraform destroy -auto-approve -force

artifacts:

  files:

     - '**/*'
